#name of CI
name: CI
#Triggers on
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17.0.11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Running Lint Debug
        run: ./gradlew lintDebug

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4.4.3
        with: 
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17.0.11'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Running Unit Test
        run: ./gradlew test

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v4.4.3
        with: 
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [lint]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '17.0.11'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run Android Emulator and Espresso Tests
      uses: ReactiveCircus/android-emulator-runner@v2.33.0
      with:
        api-level: 30
        target: default
        arch: arm64-v8a  # Use ARM architecture for Apple Silicon
        profile: Nexus 6
        emulator-options: '-no-window -no-boot-anim'
        script: adb wait-for-device && ./gradlew connectedCheck

    - name: Upload Instrumentation Test Report
      uses: actions/upload-artifact@v4.4.3
      with:
        name: instrumentation-test-report
        path: app/build/reports/androidTests/connected/


