#name of CI
name: CI
#Triggers on
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Running Lint Debug
        run: ./gradlew lintDebug

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4.4.3
        with: 
          name: index.html
          path: app/build/report/lint-results-debug.html

